---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim

  roles:
    - geerlingguy.dotfiles
